### PR TITLE
mobile: fix onboarding

### LINKED ISSUE #615: Onboarding Redesign
Collecting some ideas:
- Communication
    - explain USDC, rollups: global, snappy, secure
    - Explain self custody and device keys succinctly and well:
        - vault animation, this is your responsibility, you can't call customer support, on your device only, key can't ever leave device, no one else has access, there's no bank
        - https://github.com/daimo-eth/daimo/pull/606#discussion_r1449390992
        - another analogy we could lean into is how WhatsApp shows key rotations in chat
- Transitions
    - Make it feel progressive and fast
    - Progress bar
        - Family has a nice style: 
        - 
 - Illustrations
     - Icons feel very dated, use custom/more beautiful illustrations, maybe more color?
- lot of people don't swipe through the intro pages, perhaps convert it to something like #612 to make it a single pager and short copy like the landing page https://daimo.com
- Existing account flow improvement
    - If you select restore from backup, we should stop showing the QR code at the top and make it clear to the user what's currently being done. Related: #613 
- invite code / paste link screen
    - on valid invite show sender profile picture etc
    - lean more on social proof, show other users in extra bottom space
- use existing screen
    -  improve copy for add device scan so people don't use regular QR reader
- don't increment phone number during add device
- https://github.com/daimo-eth/daimo/issues/619
- others...?

### PR DESCRIPTION
**Pull request by dcposch**
update onboarding based on observations during edge city denver. make sure people don't get stuck on Intro or Invite page.

image

first part of #615

### CODE REVIEW

**Comment by nalinbhardwaj** [comment]
I don't think this should close #615

File: apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx [hunk 1]
```diff
@@ -62,14 +84,26 @@ export function IntroPages({
           <View style={styles.introButtonsWrap}>
             <ButtonBig
               type="primary"
-              title="Create Account"
+              title="ACCEPT INVITE"
```
Comment (nalinbhardwaj) [inline apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx:87]: was this really the gap you think?
my observations:
- a number of people (at least 3) clicked "open in app" on the web page -- we used to say "Already have it? Open in app", I think that copy was better to prevent that
- on the invite page itself people would click into the text bar and not notice the button below, I think we should just delete the text input or make it one clicks away, a secondary / text button with copy like "Manually type invite?"
- On create account we should add a pending Op to prevent users from getting confused why they didn't get their signup bonus

**Review by nalinbhardwaj — APPROVED** [review]
happy to put the other changes in a separate PR if you prefer

File: apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx (hunk 1 above)
Comment (dcposch) [reply apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx:87]: see designs in #615

Comment (dcposch) [reply apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx:87]: first and third point sgtm, will do on this PR

**Comment by dcposch** [comment]
image
image
image
image

File: packages/daimo-common/src/invite.ts [hunk 2]
```diff
@@ -9,12 +9,25 @@ import {
...
+
+  // Is it a link?
+  const link = parseDaimoLink(str);
+  if (link != null && link.type === "invite") {
+    return link;
+  } else if (link != null && link.type === "notev2") {
+    return stripSeedFromNoteLink(link);
+  }
+
+  return undefined;
```
Comment (nalinbhardwaj) [inline packages/daimo-common/src/invite.ts:30]: couldn't it also be a request link with `isValidInvite: true`?

File: packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift [hunk 3]
```diff
@@ -18,8 +18,8 @@ public class DaimoAppDelegate: ExpoAppDelegateSubscriber {
     
     if self.isOnMac() {
       UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }.forEach { windowScene in
-        windowScene.sizeRestrictions?.minimumSize = CGSize(width: 500, height: 900)
-        windowScene.sizeRestrictions?.maximumSize = CGSize(width: 500, height: 900)
+        windowScene.sizeRestrictions?.minimumSize = CGSize(width: 500, height: 1000)
```
Comment (nalinbhardwaj) [inline packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift:21]: telegram is smaller than 900 even, but lgtm

**Review by nalinbhardwaj — APPROVED** [review]

File: packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift (hunk 3 above)
Comment (dcposch) [reply packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift:21]: fixes a bug where the cancel payment link button was cut off

image

File: packages/daimo-common/src/invite.ts (hunk 2 above)
Comment (dcposch) [reply packages/daimo-common/src/invite.ts:30]: just requestv2, right? fixed

File: packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift (hunk 3 above)
Comment (nalinbhardwaj) [reply packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift:21]: I don’t think this fixes that? That happens on mobile too, probably need to change the 450s here: https://github.com/daimo-eth/daimo/blob/955e25bb2844e923b2d166bd8d23af1107d2dc98/apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx#L72

Comment (dcposch) [reply packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift:21]: ah i thought it was a percentage. fixed

Comment (dcposch) [reply packages/daimo-expo-app-delegate/ios/DaimoAppDelegate.swift:21]: image
