### PR TITLE
fix: Android 28 to 30 don't have getSecurityLevel

### LINKED ISSUE #193: Android ExpoEnclave: No getSecurityLevel?
From Lucas, Android 11, Galaxy A50

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Closes #193, tested on simulator API 29.

### CODE REVIEW

File: packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt [hunk 1]
```diff
@@ -58,8 +58,13 @@ class ExpoEnclaveModule(context: Context) : ExportedModule(context) {
...
     var keyFactory = KeyFactory.getInstance(secretKey.getAlgorithm(), KEYSTORE_PROVIDER)
     var keyInfo = keyFactory.getKeySpec(secretKey, KeyInfo::class.java)
-    
-    return keyInfo.getSecurityLevel() == KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT
+
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+      // isInsideSecureHardware is deprecated by API Level 31 (S)
+      return keyInfo.getSecurityLevel() == KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT    
+    } else {
+      return keyInfo.isInsideSecureHardware()
```
Comment (dcposch) [inline packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt:66]: 👍

**Review by dcposch — APPROVED** [review]
Clean and simple, LGTM
