### PR TITLE
Use Keyboard Avoiding View on Send screen

### LINKED ISSUE #168: Make app UX work nicely on iPhone SE (small screen, iOS 15)
Many problems ATM, should probably run through with simulator and do a pass on all pages/flows:

- Send screen: Keyboard covering the amount due small screen
    - 
- Account page: Scroll is broken, springs to the top if you try
    - 
- Home: No recent transactions visible, prob due screen size?
    - If you keep trying to scroll hard enough from the very bottom eventually do manage to trigger opening the history page somehow by accident
    -

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Closes #168 

The other two were fixed by the other PRs incidentally (add/remove made account page scrollable, #165 made recent transactions attached to the bottom)

### CODE REVIEW

File: apps/daimo-mobile/src/view/screen/send/SendScreen.tsx [hunk 1]
```diff
@@ -64,36 +70,40 @@ export default function SendScreen({ route }: Props) {
...
-                  noteCreated ? "Payment link created" : "Creating payment link"
-                }
-                dollars={noteDollars}
-                onSetDollars={noteCreated ? undefined : setNoteDollars}
-                onCancel={noteCreated ? undefined : search}
-              />
-            )}
-          </>
-        )}
+        <KeyboardAvoidingView behavior="position" keyboardVerticalOffset={128}>
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/send/SendScreen.tsx:73]: lgtm. can you post a screenshot?

Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/send/SendScreen.tsx:73]: Before and after
