### PR TITLE
expo-enclave: error bubbling to user, small bug fixes

### LINKED ISSUE #288: Handle case when we can't determine user presence
Daimo tries to authenticate the user before each transaction.

## Auth user experiences

User tries to transact. Then:

### Current

| Phone | Key manager | PIN set? | What happens |
|--------|--------|--------|----|
| iPhone | `SecureEnclaveKeyManager.swift` | yes | 🟢 prompts FaceID, TouchID or passcode |
| iPhone | `SecureEnclaveKeyManager.swift` | no | 🔴 error `passcode not set` |
| iOS simulator | `FallbackKeyManager.swift` | either way | 🟡 works without auth |
| Recent Android | `BiometricsKeyManager.kt` | yes | 🟢 Prompts fingerprint or PIN |
| Recent Android | `BiometricsKeyManager.kt` | no | ?? |
| Old/bad Android | `BiometricsKeyManager.kt` | either | ?? |
| Old/bad Android | `FallbackKeyManager.kt` | either | 🟡 works without auth |

### Goal

| Phone | Key manager | PIN set? | What happens |
|--------|--------|--------|----|
| iOS 15+ | `SecureEnclaveKeyManager.swift` | yes | 🟢 prompts FaceID, TouchID or PIN |
| iOS 15+ | `SecureEnclaveKeyManager.swift` | no | 🔴 error `Passcode not set` |
| pre-iOS 15 | N/A | N/A | N/A, unsupported |
| iOS simulator | `FallbackKeyManager.swift` | no | test only, works without auth* |
| Android 30+ | `Android30PlusKeyManager.kt` | yes | 🟢 prompts biometric or PIN |
| Android 30+ | `Android30PlusKeyManager.kt` | no | 🔴 error `PIN not set` |
| Android 28/29 | `FallbackKeyManager.kt` | yes | 🟢 prompts biometric or PIN |
| Android 28/29 | `FallbackKeyManager.kt` | no | 🔴 error `Auth failed. PIN not set?` |
| Android pre-28 | N/A | N/A | N/A, unsupported |

Daimo supports iOS 15 and later. iOS 15 supports iPhone 6s and later. This means that every iOS device we run has an Apple A9 or later SoC. As far as I can tell, **all iOS devices the app runs on have Secure Enclave.**

*The only reason we need the `FallbackKeyManager` on iOS is for testing. The iOS simulator doesn't have a Secure Enclave and doesn't support passcodes.

Daimo supports Android 9 Pie ("API Level 28") and later.

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Closes #288

### CODE REVIEW

File: apps/daimo-mobile/src/action/useExistingAccount.ts [hunk 1]
```diff
@@ -6,14 +6,11 @@ import { rpcFunc } from "../logic/trpc";
 import { useTime } from "../logic/useTime";
 import { defaultEnclaveKeyName, useAccount } from "../model/account";
 
-export function useExistingAccount(forceWeakerKeys: boolean) {
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/useExistingAccount.ts:9]: 👍 👍

File: apps/daimo-mobile/src/action/useCreateAccount.ts [hunk 2]
```diff
@@ -7,17 +7,11 @@ import { rpcHook } from "../logic/trpc";
...
+export function useCreateAccount(name: string): ActHandle {
   const [as, setAS] = useActStatus();
 
-  const enclaveKeyInfo = {
-    name: defaultEnclaveKeyName,
-    forceWeakerKeys,
-  };
-  const pubKeyHex = useLoadOrCreateEnclaveKey(setAS, enclaveKeyInfo);
+  const enclaveKeyName = defaultEnclaveKeyName;
+  const pubKeyHex = useLoadOrCreateEnclaveKey(setAS, enclaveKeyName);
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/useCreateAccount.ts:14]: nice simplification

File: apps/daimo-mobile/src/action/useSendAsync.ts [hunk 3]
```diff
@@ -126,14 +126,19 @@ async function sendAsync(
     return handle;
   } catch (e: any) {
     console.error(e);
-    if (keySlot === undefined) setAS("error", "Device removed from account");
-    else setAS("error", "Error sending transaction");
+    if (keySlot === undefined) {
+      setAS("error", "Device removed from account");
+    } else if (e instanceof NamedError && e.name === "ExpoEnclaveSign") {
+      setAS("error", e.message);
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/useSendAsync.ts:132]: so this passes thru `Passcode not set` etc

File: apps/daimo-mobile/src/logic/log.ts [hunk 4]
```diff
@@ -5,6 +5,16 @@ interface LogAction {
   error?: string;
 }
 
+export class NamedError extends Error {
+  constructor(message: string, public name: string) {
+    super(message);
+
+    // Set the prototype explicitly.
+    // https://github.com/microsoft/TypeScript-wiki/blob/81fe7b91664de43c02ea209492ec1cea7f3661d0/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
+    Object.setPrototypeOf(this, NamedError.prototype);
```
Comment (dcposch) [inline apps/daimo-mobile/src/logic/log.ts:14]: just curious, what was the issue that this fixed?

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 5]
```diff
@@ -99,24 +100,17 @@ export default function OnboardingScreen({
...
     <View style={styles.onboardingScreen}>
       {page === "intro" && <IntroPages onNext={next} />}
       {(page === "create-try-enclave" || page === "existing-try-enclave") && (
-        <TryEnclave
-          onNext={next}
-          createStatus={createStatus}
-          forceWeakerKeys={forceWeakerKeys}
-          setForceWeakerKeys={setForceWeakerKeys}
-        />
+        <SetupKey onNext={next} createStatus={createStatus} />
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:113]: much nicer

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 6]
```diff
@@ -298,16 +272,16 @@ function TryEnclave({
...
-        const err = `[ONBOARDING] Failed with weaker keys too, giving up`;
-        setError(err);
-        console.error(err);
+        setError("Unknown error");
       }
+
+      // Assume user doesn't have proper auth set up.
+      // TODO: In future, catch different errors differently and
+      // show a retry button in case user intentionally cancelled auth.
+      setAskToSetPin(true);
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:284]: we can show a catch-all like `Auth failed. PIN not set?`

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 7]
```diff
@@ -316,21 +290,21 @@ function TryEnclave({
...
                 account. This makes your money yours alone.
               </TextBody>
             )}
-            {askWeak && (
+            {askToSetPin && (
               <TextBody>
-                Failed to create hardware authenticated key. This can happen on
-                older Android devices. Use regular key?
+                Your device does not appear to have a secure lock screen (PIN or
+                biometrics) set up. Please set one up and try again.
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:307]: given this will also show up the user cancels (and potentially other device issues), maybe

```
const noun = platform === 'android' ? 'lock screen' ? 'passcode';
```
```
Authentication failed. Does your phone have a ${noun}? You'll need one to secure your Daimo account.```

**Review by dcposch — APPROVED** [review]
LGTM, left comments

File: apps/daimo-mobile/src/action/useSendAsync.ts (hunk 3 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/action/useSendAsync.ts:132]: yep

File: apps/daimo-mobile/src/logic/log.ts (hunk 4 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/logic/log.ts:14]: no observed issue but other code online recommended adding it (and the typescript github link explains why)

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx (hunk 6 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:284]: we display the error from expo enclave module in red and we do have a try again button now so that comment is slightly outdated (will fix). Will include your other copy suggestion and then I think we should be good to go.

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx (hunk 7 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:307]: This screen is android only. Will update copy with noun = `lock screen (PIN or biometrics)`.
