### PR TITLE
Release bug fixes

### LINKED ISSUE #233: ENS Resolution in Recent transactions takes a second
Flow: Send to `yolo.eth`, get redirected to Home Screen. For a second, the recent transactions first flash "0x..." hex address before switching to "yolo.eth". We should be able to make it one swift motion/reliable.

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
mainnet testing todos:

- [x] alert if account deployer wallet balance is low
- [x] on-ramp USDC (Base Native) vs. USDC
- [x] android icon centering on key generation screen
- [x] flash of 0x… for pending payment to ENS
    - Closes #233 
- [x] resync on notification
    - stopgap reduce regular sync time from 30 secs to 10
- [x] flash of 0x… on claiming payment link
- [x] website “$1.00” not “$1”
- [x] website “or already claimed” weird nextjs caching?
- [x] website logo reduce size
- [x] history header is incorrectly transparent
- [x] Coinbase embed needs safe header area
- [x] paymaster deposit low

### CODE REVIEW

File: apps/daimo-mobile/src/action/useSendAsync.ts [hunk 1]
```diff
@@ -62,10 +62,18 @@ export function useSendAsync({
       pendingOp.timestamp = Math.floor(Date.now() / 1e3);
       pendingOp.feeAmount = Number(dollarsToAmount(feeDollars));
 
+      // Filter to new named accounts
+      namedAccounts = (namedAccounts || []).filter(
+        (acc) =>
+          account.namedAccounts.find(
+            (alreadyNamed) => alreadyNamed.addr === acc.addr
+          ) == null
+      );
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/useSendAsync.ts:71]: minor but i'd do

```ts
const findAccount = (addr: Address) => account.namedAccounts.find((a) => a.addr === addr);
namedAccounts = (namedAccounts || []).filter((a) => findAccount(a) == null)
```

File: apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx [hunk 2]
```diff
@@ -149,6 +151,12 @@ function NoteDisplayInner({
       timestamp: Date.now() / 1e3,
       nonceMetadata: nonceMetadata.toHex(),
     },
+    namedAccounts: [
+      {
+        addr: daimoEphemeralNotesAddress,
+        label: AddrLabel.PaymentLink,
+      } as EAccount,
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx:158]: 👍

File: packages/daimo-api/src/api/deployWallet.ts [hunk 3]
```diff
@@ -56,7 +56,7 @@ export async function deployWallet(
 
   const explorer = chainConfig.chainL2.blockExplorers!.default.url;
   const url = `${explorer}/address/${address}`;
-  telemetry.recordClippy(`New user ${name} at ${url}`, "info");
+  telemetry.recordClippy(`New user ${name} at ${url}`, "celebrate");
```
Comment (dcposch) [inline packages/daimo-api/src/api/deployWallet.ts:59]: lol lgtm

File: packages/daimo-api/src/cron.ts [hunk 4]
```diff
@@ -68,12 +69,31 @@ export class Crontab {
...
+    });
+    const balanceEth = Number(formatEther(balance));
+    if (balanceEth < 0.002) {
+      this.telemetry.recordClippy(
+        `Faucet ${faucetAddr} balance too low: ${balanceEth} eth`,
+        "error"
+      );
+    } else if (balanceEth < 0.02) {
+      this.telemetry.recordClippy(
+        `Faucet ${faucetAddr} balance low: ${balanceEth} eth`,
```
Comment (dcposch) [inline packages/daimo-api/src/cron.ts:96]: 🚀 

we can even make this 0.01 (too low) and 0.05 (low) so we have time to fix it

File: packages/daimo-common/src/daimoLink.ts [hunk 5]
```diff
@@ -123,7 +123,7 @@ function parseDaimoLinkInner(link: string): DaimoLink | null {
         previewSender = parts[1];
         const parsedDollars = zDollarStr.safeParse(parts[2]);
         if (!parsedDollars.success) return null;
-        previewDollars = parsedDollars.data;
+        previewDollars = parseFloat(parsedDollars.data).toFixed(2) as DollarStr;
```
Comment (dcposch) [inline packages/daimo-common/src/daimoLink.ts:126]: 👍

Comment (dcposch) [reply packages/daimo-common/src/daimoLink.ts:126]: we can also fix this one the link creation side -- the link should be `/1.00` not `/1`

**Review by dcposch — APPROVED** [review]
LGTM

File: packages/daimo-common/src/daimoLink.ts (hunk 5 above)
Comment (nalinbhardwaj) [reply packages/daimo-common/src/daimoLink.ts:126]: probably better to keep them shorter

File: packages/daimo-api/src/cron.ts (hunk 4 above)
Comment (nalinbhardwaj) [reply packages/daimo-api/src/cron.ts:96]: 0.02 is nearly 50+ user onboardings at current gas costs, should be fine

File: apps/daimo-mobile/src/action/useSendAsync.ts (hunk 1 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/action/useSendAsync.ts:70]: done

File: apps/daimo-web/src/app/link/[[...slug]]/page.tsx [hunk 6]
```diff
@@ -29,7 +32,7 @@ type TitleDesc = {
 
 const domain = process.env.NEXT_PUBLIC_DOMAIN;
 
-const defaultMeta = metadata("Daimo", "Experimental stablecoin wallet");
+const defaultMeta = metadata("Daimo", "Payments App on Ethereum");
```
Comment (dcposch) [inline apps/daimo-web/src/app/link/[[...slug]]/page.tsx:35]: maybe just `Payments on Ethereum`

Comment (nalinbhardwaj) [reply apps/daimo-web/src/app/link/[[...slug]]/page.tsx]: done

File: apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx [hunk 7]
```diff
@@ -63,6 +63,12 @@ export default function DepositScreen() {
         <Spacer h={16} />
         <AddressCopier addr={account.address} />
       </View>
+      <View style={styles.callout}>
+        <TextBody>
+          <Octicons name="alert" size={16} color="black" /> Send USDC (Base
+          Native) only. Daimo does not support other tokens.
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx:69]: ^ maybe add to box something like

> **Deposit {tokenSymbol} on {chainL2.name} only.**
> {tokenSymbol === "USDC" && chainL2.name === "Base" && 'Use native USDC, not bridged "USDbC".'}
> Use the following address.

Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx]: done
