### PR TITLE
fix: stop assuming that one tx has one userop

### LINKED ISSUE #210: Fix fetchNonceMetadata assumption that one tx has one userop

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Tested request tracking still works:

Closes #210

### CODE REVIEW

File: packages/daimo-api/src/contract/opIndexer.ts [hunk 1]
```diff
@@ -37,7 +37,12 @@ export class OpIndexer {
   private parseLogs = (logs: userOperationLog[]) => {
     for (const log of logs) {
       if (log.transactionHash) {
-        this.txHashToUserOp.set(log.transactionHash, log);
+        const curLogs = this.txHashToSortedUserOps.get(log.transactionHash);
+        const newLogs = curLogs ? [...curLogs, log] : [log];
+        this.txHashToSortedUserOps.set(
+          log.transactionHash,
+          newLogs.sort((a, b) => a.logIndex - b.logIndex)
+        );
```
Comment (dcposch) [inline packages/daimo-api/src/contract/opIndexer.ts:45]: minor but this can be simplified to

```ts
const logs = this.txHashToSortedUserOps.get(log.transactionHash) || [];
this.txHashToSortedUserOps.set(log.transactionHash, logs);
logs.push(log);
logs.sort((a, b) => a.logIndex - b.logIndex);
```

File: packages/daimo-api/src/router.ts [hunk 2]
```diff
@@ -223,7 +223,10 @@ export function createRouter(
         const transferLogs = rawLogs.map((log) => {
           const { blockNumber, blockHash, logIndex, transactionHash } = log;
           const { from, to, value } = log.args;
-          const nonceMetadata = opIndexer.fetchNonceMetadata(transactionHash);
+          const nonceMetadata = opIndexer.fetchNonceMetadata(
```
Comment (dcposch) [inline packages/daimo-api/src/router.ts:226]: 👍 👍

**Review by dcposch — APPROVED** [review]
LGTM
