### PR TITLE
 mobile: storedTypes, migrate to StoredV16Account 

### LINKED ISSUE #1181: Crash on logging into existing account
## Summary

I logged back into my account and got an app crash. Debug log reveals error under `isNativeETH` call.

On prod API + latest testflight app:

```
{
  "Platform": "ios 17.6 phone",
  "Version": "1.9.1 #438",
  "Commit": "0a575621 production",
  "Notifications": "enabled",
  "Key Security": "secure enclave",
  "amountSeparator": "."
}
```

### PR DESCRIPTION
**Pull request by dcposch**
fixes #1181

### CODE REVIEW

File: apps/daimo-mobile/src/storage/account.ts [hunk 1]
```diff
@@ -0,0 +1,308 @@
...
+  enclavePubKey: Hex;
+  /** Daimo name, registered onchain */
+  name: string;
+  /** Contract wallet address */
+  address: Address;
+
+  /** Home chain where we hold our balance */
+  homeChainId: number;
+  /** Home ERC-20 token where we hold our balance */
+  homeCoinAddress: Address;
```
Comment (kayleegeorge) [inline apps/daimo-mobile/src/storage/account.ts:58]: for next account version: thoughts on having `homeCoinToken: ForeignToken` or should we just have some function that grabs the ForeignToken from the address?

File: packages/daimo-common/src/foreignToken.ts [hunk 2]
```diff
@@ -83,26 +101,22 @@ export function isAmountDust(
...
-      return baseSepolia.nativeETH;
+      return baseSepolia.nativeWETH;
   }
 }
 
-// Token is native ETH to the given chainConfig.
+// Checks if the token ETH or native WETH on the given chain.
 export function isNativeETH(
-  tokenAddress: Address,
+  token: ForeignToken,
```
Comment (kayleegeorge) [inline packages/daimo-common/src/foreignToken.ts:117]: clean

**Review by kayleegeorge — APPROVED** [review]

**Comment by kayleegeorge** [comment]
looks good to me (note build fails though)

File: apps/daimo-mobile/src/storage/storedTypes.ts [hunk 3]
```diff
@@ -0,0 +1,245 @@
...
+
+//
+// Stored types used inside of StoredModels.
+//
+// Do not edit these except to add new OPTIONAL fields or enums.
+// Anything else requires a new version and a migration.
+// This file contains current types. For old versions, see storedTypeMigrations.
+//
+
+export type StoredV16Clog = StoredV16TransferClog | StoredV15PaymentLinkClog;
```
Comment (kayleegeorge) [inline apps/daimo-mobile/src/storage/storedTypes.ts:19]: note in future: change to`= SimpleTransferClog | PaymentLinkClog | SwapClog` -- which would remove `preSwapTransfer` from `TransferClog` and that whole clog will instead be a `SwapClog`
