### PR TITLE
mobile: use bitrefill new parse

### LINKED ISSUE #1356: Bitrefill stuck on checkout screen
## Summary

It looks like something broke our Bitrefill integration.

Steps to reproduce:
* Try a Bitrefill deposit
* Click Pay
* Expected result: Daimo bottomsheet to complete payment
* Actual: infinite spinner in the Bitrefill webapp, no bottomsheet

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
closes #1356

### CODE REVIEW

File: apps/daimo-mobile/src/action/dispatch.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export type Action =
   | { name: "createBackup" }
   | { name: "hideBottomSheet" }
   | { name: "swap"; swap: ProposedSwap }
-  | { name: "bitrefill"; address: Address; amount: DollarStr };
+  | { name: "bitrefill"; address: Address; amount: BigIntStr };
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/dispatch.ts:16]: 👍

File: apps/daimo-mobile/src/logic/paymentURI.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+  const amount = params.get("uint256");
+
+  if (!recipientAddress || !isAddress(recipientAddress)) {
+    throw new Error("Invalid recipient address");
+  }
+  if (!amount) throw new Error("Missing amount");
+
+  return {
+    recipientAddress: getAddress(recipientAddress),
+    amount: BigInt(Number(amount)).toString() as BigIntStr,
```
Comment (dcposch) [inline apps/daimo-mobile/src/logic/paymentURI.ts:35]: i think `BigInt(Number(amount))` can be slightly off due to double precision

File: apps/daimo-mobile/src/view/screen/deposit/BitrefillWebview.tsx [hunk 3]
```diff
@@ -22,29 +21,12 @@ export function BitrefillWebView() {
...
-          assert(protocol === "ethereum");
-          const [address, queryString] = rest.split("?");
-          const params = new URLSearchParams(queryString);
-
-          const parsedUri = PaymentUriSchema.parse({
-            protocol,
-            address,
-            amount: params.get("amount") || "",
-          });
+          const parsedUri = parsePaymentUri(paymentUri);
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/deposit/BitrefillWebview.tsx:25]: 👍

File: apps/daimo-mobile/test/paymentURI.test.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+  // https://github.com/daimo-eth/daimo/issues/1356
+  it("Parses Bitrefill URI", () => {
+    const uri = parsePaymentUri(
+      `ethereum:0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359@137/transfer?address=0xaCB6230043d1Fc3dE02a43Aa748540bb9F260931&uint256=1e8`
+    );
+
+    expect(uri.recipientAddress).toEqual(
+      "0xaCB6230043d1Fc3dE02a43Aa748540bb9F260931"
+    );
+    expect(uri.amount).toEqual("100000000");
```
Comment (dcposch) [inline apps/daimo-mobile/test/paymentURI.test.ts:13]: 🚀

File: apps/daimo-mobile/src/logic/paymentURI.ts (hunk 2 above)
Comment (dcposch) [reply apps/daimo-mobile/src/logic/paymentURI.ts:35]: also, actually it's totally fine for USDC. issue only happens with 18-decimal tokens

**Review by dcposch — APPROVED** [review]
LGreatTM
