### PR TITLE
fix: send, cleaner useSendAsync, note > payment link

### LINKED ISSUE #77: Create Note clarity
Ulas: "I didn't realize I was creating a burner wallet"

### PR DESCRIPTION
**Pull request by dcposch**
fixes #77 

 - [x] note > link
 - [x] explain what a Payment Link is. subtitle “This will create a link that can be redeemed by anyone with a Daimo account or an Ethereum wallet”

### CODE REVIEW

File: apps/daimo-mobile/src/action/useSendAsync.ts [hunk 1]
```diff
@@ -59,17 +59,17 @@ export function useWarmCache(enclaveKeyName?: string, address?: Address) {
 const accountCache: Map<string, Promise<DaimoAccount>> = new Map();
```
Comment (nalinbhardwaj) [inline apps/daimo-mobile/src/action/useSendAsync.ts:59]: nit: `Map<Address, ...>`

**Comment by dcposch** [comment]
## Clean up SendScreen, useSendAsync

fixes #68 

image
