### PR TITLE
android: add onboarding step to resolve key issues

### LINKED ISSUE #215: Android enclave broken on some phone models
## Problem

- Ying Tong: can't send. TODO: get Debug Log
- Lev: can't send, "my fingerprint reader is broken".

~Others people have experienced the `missing getSecurityLevel()` error.~ #193

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
New step flow:

Closes #215 : Both YT's and Lev's issue should be dealt with now.

### CODE REVIEW

File: packages/daimo-expo-enclave/src/index.ts [hunk 1]
```diff
@@ -39,6 +39,14 @@ export async function getBiometricSecurityLevel(): Promise<BiometricSecurityLeve
   return ExpoEnclaveModule.getBiometricSecurityLevel();
 }
 
+/**
+ * Forcibly use software (non-hardware backed) keys. Used for smooth operation on
+ * Android where unpredictable issues with hardware-backed keys are common.
```
Comment (dcposch) [inline packages/daimo-expo-enclave/src/index.ts:44]: this makes it sound like we always use it on android

File: packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift [hunk 2]
```diff
@@ -34,6 +34,10 @@ public class ExpoEnclaveModule: Module {
       }
     }
 
+    AsyncFunction("forceFallbackUsage") { () in
+      keyManager = FallbackKeyManager()
```
Comment (dcposch) [inline packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift:38]: is it possible to put this into a constructor or `init` so that we initialize `keyManager` once?

having this imperative function feels bad, but OK if it's the only way

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 3]
```diff
@@ -228,6 +260,130 @@ function PageBubble({ count, index }: { count: number; index: number }) {
...
+      }
+    }
+    setLoading(false);
+  };
+
+  return (
+    <View style={styles.onboardingScreen}>
+      <View style={styles.createAccountPage}>
+        <TextH1>
+          <Octicons name="unlock" size={40} color={askWeak ? "red" : "black"} />
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:318]: recommend following instead:

```tsx
<Octicons name={askWeak ? "unlock" : "lock"} size={32} />
```

File: apps/daimo-mobile/src/action/useSendAsync.ts [hunk 4]
```diff
@@ -132,16 +153,27 @@ async function sendAsync(
   }
 }
 
-async function requestEnclaveSignature(enclaveKeyName: string, hexTx: string) {
+export async function requestEnclaveSignature(
+  enclaveKeyName: string,
+  hexTx: string,
+  usageMessage: string,
+  forceWeakerKeys: boolean
```
Comment (dcposch) [inline apps/daimo-mobile/src/action/useSendAsync.ts:160]: so i think we now need `forceWeakerKeys` everywhere we use `enclaveKeyName`. i wonder if it's worth extracting an `EnclaveKeyInfo` that looks something like

```
interface EnclaveKeyInfo {
  keyName: string
  keyType: <"software" | "hardware">
}
```

Comment (dcposch) [reply apps/daimo-mobile/src/action/useSendAsync.ts:160]: bit less code in a lot of places, eg here we'd pass `keyInfo: EnclaveKeyInfo`

since figuring out the `keyType` on existing accounts might be inconvenient in the migration, you could also say

```ts
interface EnclaveKeyInfo {
  keyName: string
  forceWeakerKeys: boolean
}
```

**Review by dcposch — COMMENTED** [review]
LGTM, left comments

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 5]
```diff
@@ -228,6 +260,130 @@ function PageBubble({ count, index }: { count: number; index: number }) {
...
+          <TextCenter>
+            {!askWeak && (
+              <TextBody>
+                Create a cryptographic key on-device that will authorize your
+                account. This makes your money yours alone.
+              </TextBody>
+            )}
+            {askWeak && (
+              <TextBody>
+                Failed to create a hardware enclave authenticated key. Use
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:331]: might be worth saying something like

> Failed to create hardware authenticated key. This can happen on older Android devices. Use software key?

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx [hunk 6]
```diff
@@ -228,6 +260,130 @@ function PageBubble({ count, index }: { count: number; index: number }) {
...
+        <TextH1>
+          <Octicons name="unlock" size={40} color={askWeak ? "red" : "black"} />
+        </TextH1>
+        <Spacer h={32} />
+        <View style={ss.container.padH16}>
+          <TextCenter>
+            {!askWeak && (
+              <TextBody>
+                Create a cryptographic key on-device that will authorize your
+                account. This makes your money yours alone.
```
Comment (dcposch) [inline apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:326]: 🚀

File: packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift (hunk 2 above)
Comment (nalinbhardwaj) [reply packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift:38]: Yeah, I also wanted to do that but afaict we have no control over `ExportedModule` life cycles and the constructor/`init` is called before we can inject custom arguments in runtime.

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx (hunk 3 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:318]: done; changed size to 40 to keep it consistent with "bell" size on notifications screen.

File: apps/daimo-mobile/src/action/useSendAsync.ts (hunk 4 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/action/useSendAsync.ts:160]: done latter since easier + also technically we only need to know whether we need to force the enclave or not. If not we can save a call as it can autodetect key being software or hardware.

File: apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx (hunk 5 above)
Comment (nalinbhardwaj) [reply apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx:331]: done

File: packages/daimo-expo-enclave/src/index.ts (hunk 1 above)
Comment (nalinbhardwaj) [reply packages/daimo-expo-enclave/src/index.ts:44]: fixed
