### PR TITLE
telemetry: log reverted txes, increase paymaster warns

### LINKED ISSUE #891: Observability: link directly to correct debug trace on every failed or reverted op
## Goal

Whenever a user tries to transact and fails or the transaction reverts, we should get:
- exactly one alert, and
- the alert should link directly to a correct and complete trace, such as [this one](https://basescan.org/vmtrace?txhash=0x07a55b03e90b0c8fe555b2fb3ce76680ba5c66f7966b17ca0301a28643c2b022&type=gethtrace2)

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Closes #891 

image
^purposefully broke signatures sent by client

### CODE REVIEW

File: packages/daimo-api/src/env.ts [hunk 1]
```diff
@@ -1,5 +1,10 @@
 import { DaimoChain, getChainConfig } from "@daimo/contract";
 
+// Enable JSON.stringify for BigInts
```
Comment (dcposch) [inline packages/daimo-api/src/env.ts:3]: i'm very dubious of these kinds of global edits, but in this case i think it's OK

File: packages/daimo-api/src/network/viemClient.ts [hunk 2]
```diff
@@ -83,6 +85,30 @@ export class ViemClient {
...
+    try {
+      const receipt = await this.publicClient.waitForTransactionReceipt({
+        hash,
+      });
+      console.log(`[CHAIN] waitForReceipt ${hash}: ${JSON.stringify(receipt)}`);
+      if (receipt.status !== "success") {
+        this.onReceiptError(hash, JSON.stringify(receipt));
+      }
+    } catch (e) {
+      console.log(`[CHAIN] waitForReceipt error: ${e}`);
```
Comment (dcposch) [inline packages/daimo-api/src/network/viemClient.ts:107]: console.error

File: packages/daimo-api/src/server/cron.ts [hunk 3]
```diff
@@ -111,8 +111,8 @@ export class Crontab {
     await this.sendLowBalanceMessage(
       depositEth,
       `Paymaster ${daimoPaymasterV2Address} ETH`,
-      isMetaPaymasterEnabled ? 0.01 : 0.03,
-      isMetaPaymasterEnabled ? 0.005 : 0.01
+      isMetaPaymasterEnabled ? 0.01 : 0.1,
+      isMetaPaymasterEnabled ? 0.005 : 0.2
```
Comment (dcposch) [inline packages/daimo-api/src/server/cron.ts:115]: 👍

File: packages/daimo-api/src/env.ts (hunk 1 above)
Comment (nalinbhardwaj) [reply packages/daimo-api/src/env.ts:3]: Agree - I think in this case there's a great chance of bugs being caused by console logs/warnings/errors crashing due to lack of this rather than the other way around.

File: packages/daimo-api/src/network/viemClient.ts (hunk 2 above)
Comment (nalinbhardwaj) [reply packages/daimo-api/src/network/viemClient.ts]: done
