### PR TITLE
fix @daimo/userop: remove unnecessary RPC, fix op building

### LINKED ISSUE #256: Base public RPC has low limits
fine for testbed, for prod this public RPC has low limits

_Originally posted by @dcposch in https://github.com/daimo-eth/daimo/pull/255#discussion_r1322745674_

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
tested on simulators txes still work fine and sync etc. looks clean :)

drops dependency on userop.js `Client` object and instead recreates the relevant functionality (`eth_sendUserOperation`) in our own code.

Closes #256

### CODE REVIEW

File: apps/daimo-mobile/src/action/useSendAsync.ts [hunk 1]
```diff
@@ -50,17 +49,14 @@ export function useSendAsync({
...
       pendingOp.timestamp = Math.floor(Date.now() / 1e3);
       account.recentTransfers.push(pendingOp);
       account.namedAccounts.push(...(namedAccounts || []));
       // TODO: add pending device add/removes
       console.log(`[SEND] added pending op ${pendingOp.opHash}`);
 
       setAccount(account);
-
-      // In the background, wait for the op to finish
-      handle.wait().then(() => resync(`op finished: ${pendingOp.opHash}`));
```
Comment (nalinbhardwaj) [inline apps/daimo-mobile/src/action/useSendAsync.ts:63]: just to double check @dcposch this `resync` isn't really necessary right? afaict since we have a pending op it resyncs at high frequency anyway?

Comment (dcposch) [reply apps/daimo-mobile/src/action/useSendAsync.ts:63]: ya, not necessary, feel free to drop

File: apps/daimo-testbed/App.tsx [hunk 2]
```diff
@@ -56,19 +49,14 @@ export default function App() {
       "P-256 Public Key, deploy corresponding account by calling createAccount on factory:",
       derPublicKey
     );
-    const account = await DaimoOpSender.init(
-      accAddress,
-      signer,
-      "https://goerli.base.org",
```
Comment (dcposch) [inline apps/daimo-testbed/App.tsx:62]: 🚀

File: packages/daimo-contract/script/fetchTokenMetadata.ts [hunk 3]
```diff
@@ -40,13 +40,13 @@ async function main() {
...
   });
+  const chainId = baseGoerli.id;
 
   // Rather than call Pimlico SDK's getERC20Paymaster which makes
   // network requests and needs a ethers provider, we just hardcode
   // the create2 address computation call here for efficiency.
-  const oracle_address = ORACLE_ADDRESS[baseGoerli.id]["USDC"];
-  const nativeAssetOracle =
-    ORACLE_ADDRESS[baseGoerli.id][NATIVE_ASSET[baseGoerli.id]];
+  const oracle_address = ORACLE_ADDRESS[chainId]["USDC"];
```
Comment (dcposch) [inline packages/daimo-contract/script/fetchTokenMetadata.ts:48]: nit, `oracleAddress`

File: packages/daimo-userop/src/index.ts [hunk 4]
```diff
@@ -26,11 +26,11 @@ export type UserOpHandle = Awaited<
   ReturnType<typeof DaimoOpSender.prototype.sendUserOp>
 >;
 
-// TODO: use the right RPC
 // DaimoOpSender is a wrapper that simplifies making user ops on behalf of a Daimo account.
 export class DaimoOpSender {
-  private dryRun = false;
-  private client: Client;
+  /** Connection to the chain */
+  private provider: BundlerJsonRpcProvider;
```
Comment (dcposch) [inline packages/daimo-userop/src/index.ts:32]: 👍 much more specific

**Review by dcposch — APPROVED** [review]
LGreatTM

File: packages/daimo-userop/src/index.ts [hunk 5]
```diff
@@ -222,11 +213,7 @@ export class DaimoOpSender {
     return this.sendUserOp(op);
   }
 
-  /**
-   * Creates an ephemeral note with given value.
-   * Infinite-approves the notes contract first, if necessary.
```
Comment (nalinbhardwaj) [inline packages/daimo-userop/src/index.ts:227]: Fixes Veridise Audit ID 11

Comment (dcposch) [reply packages/daimo-userop/src/index.ts:227]: i recommend extracting that into its own PR

Comment (nalinbhardwaj) [reply packages/daimo-userop/src/index.ts:227]: done; #276

**Comment by dcposch** [comment]
I think there's a good argument for including this on `audit-1-fix`

Even though it doesn't directly fix an audit issue,
- It makes the doc comments in `DaimoOpSender` correct (currently they say "returns a userop hash" but actually returns an object)
- Simplifies `@daimo/userop`, net -50LOC

File: packages/daimo-contract/script/fetchTokenMetadata.ts (hunk 3 above)
Comment (nalinbhardwaj) [reply packages/daimo-contract/script/fetchTokenMetadata.ts]: done

**Review by dcposch — APPROVED** [review]
-100LOC now, very nice

File: packages/daimo-userop/src/daimoOpBuilder.ts [hunk 6]
```diff
@@ -62,7 +71,7 @@ export class DaimoOpBuilder extends UserOperationBuilder {
         Presets.Middleware.estimateUserOperationGas(instance.provider)
       )
       .useMiddleware(async (ctx) => {
-        ctx.op.verificationGasLimit = 500_000;
+        ctx.op.verificationGasLimit = DEFAULT_USEROP_VERIFICATION_GAS_LIMIT;
```
Comment (nalinbhardwaj) [inline packages/daimo-userop/src/daimoOpBuilder.ts:74]: is this change from 500k -> default intended?

Comment (dcposch) [reply packages/daimo-userop/src/daimoOpBuilder.ts:74]: yes, didn't want to hardcode in `userop`.

currently,
- verification actually costs ~400k gas, most of that in P256Verifier
- verificationGasLimit 500k **should** work
- does work in actual execution
- fails with that enigmatic "too much token" error in estimateUserOperationGas


so for now `DEFAULT_USEROP_VERIFICATION_GAS_LIMIT` is 1.5m, but we can set it to 500k once that last issue is resolved in pimlico

**Comment by nalinbhardwaj** [comment]
latest changes look great!
